version: "3.9"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=dev
    image: fuzzy-questions-app:8.3
    container_name: php
    restart: unless-stopped
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      APP_ENV: dev
      APP_DEBUG: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - '.:/app:delegated'
      - './build/config/local/php/20-xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini'
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - './build/config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/app:delegated'
    depends_on:
      - php

  postgres:
    image: 'postgres:alpine'
    container_name: postgres
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PORT: 5432
      PGPASSWORD: tmp
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: tmp
    volumes:
      - './pgsql:/var/lib/postgresql/data:delegated'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      retries: 3
      timeout: 5s
