version: "3.9"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=dev
    image: fuzzy-questions-app:8.3
    restart: unless-stopped
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      APP_ENV: dev
      APP_DEBUG: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - '.:/app:delegated'
      - './build/config/local/php/20-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './build/config/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf'
      - './build/config/php/17-php.ini:/usr/local/etc/php/conf.d/php.ini'
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - './build/config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/app:delegated'
    depends_on:
      - php

  postgres:
    image: 'postgres:alpine'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PORT: 5432
      PGPASSWORD: tmp
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: tmp
    volumes:
      - './pgsql:/var/lib/postgresql/data:delegated'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      retries: 3
      timeout: 5s
